repos:
- repo: https://github.com/pre-commit/pre-commit-hooks.git
  rev: v3.4.0
  hooks:
    - id: check-merge-conflict
    - id: trailing-whitespace
- repo: https://github.com/python/black
  rev: 21.4b2
  hooks:
    - id: black
      types: [python]
      language_version: python3
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.9.1
  hooks:
    - id: flake8
      types: [python]
      language_version: python3
      additional_dependencies: ['flake8-bugbear==20.11.1']
- repo: https://github.com/timothycrosley/isort
  rev: 5.8.0
  hooks:
    - id: isort
      types: [python]
      language_version: python3
- repo: https://github.com/PyCQA/bandit
  rev: 1.7.0
  hooks:
    - id: bandit
      types: [python]
      exclude: tests/.*$
- repo: https://github.com/asottile/pyupgrade
  rev: v2.7.4
  hooks:
    - id: pyupgrade
      args: ["--py36-plus"]
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.812
  hooks:
    - id: mypy
      name: "Type-check python in src/"
      files: ^src/.*$
      types: [python]
    - id: mypy
      name: "Type-check python in tests/"
      files: ^tests/.*$
      types: [python]
